commit

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -42,27 +42,34 @@ jobs:
           sudo systemctl start tomcat9     # Start Tomcat
           sudo systemctl enable tomcat9   # Enable Tomcat to start on boot
 
-      - name: Wait for Tomcat to start
-        run: sleep 10  # Adjust if needed to wait for Tomcat to start properly
-
+          - name: Wait for Tomcat to start
+          run: |
+            until curl -s "http://${{ env.TOMCAT_HOSTNAME }}:${{ env.TOMCAT_PORT }}" &>/dev/null; do
+              echo "Waiting for Tomcat to start..."
+              sleep 5
+            done
+        
       - name: Deploy WAR file to Tomcat
         run: |
           # Extract the base name of the artifact (removes ".war" extension)
           ARTIFACT_BASENAME=$(basename "${{ env.ARTIFACT_NAME }}" .war)
-          
+            
           curl -v -u "${{ env.TOMCAT_USERNAME }}:${{ env.TOMCAT_PASSWORD }}" \
             -T "${{ github.workspace }}/${{ env.ARTIFACT_NAME }}" \
             "http://${{ env.TOMCAT_HOSTNAME }}:${{ env.TOMCAT_PORT }}/manager/text/deploy?path=/${ARTIFACT_BASENAME}&update=true"
-
+        
       - name: Verify deployment
         run: |
-          sleep 10  # Adjust if needed to wait for deployment to complete
-          response_code=$(curl -s -o /dev/null -w "%{http_code}" \
-            "http://${{ env.TOMCAT_HOSTNAME }}:${{ env.TOMCAT_PORT }}/${{ env.ARTIFACT_NAME }}/")
+            sleep 10  # Adjust if needed to wait for deployment to complete
+            response_code=$(curl -s -o /dev/null -w "%{http_code}" \
+              "http://${{ env.TOMCAT_HOSTNAME }}:${{ env.TOMCAT_PORT }}/${{ env.ARTIFACT_NAME }}/")
+        
+            if [ "$response_code" == "200" ]; then
+              echo "Deployment successful."
+            else
+              echo "Deployment failed with HTTP status code $response_code."
+              exit 1
+            fi
+        
 
-          if [ "$response_code" == "200" ]; then
-            echo "Deployment successful."
-          else
-            echo "Deployment failed with HTTP status code $response_code."
-            exit 1
-          fi
+      
